defaults:
  - _self_

### all paths

wsi_input_folder: 

json_folder:

pickle_output_folder:

conversion_output_folder: 

simplifiedgraph_folder: 

split_output_folder: 

visualization_path: 



### graphs

# generate graph (pickle format)
pickle_output_corename: "graph_r50"
radius: 50
timing: True
with_texture: True  

# graph simplification
max_hops: 3
 
# graph splitting
split_from_simplified: True   
nbr_subgraphs: 100 

# graph visualization
graphtype: dataset  #[dataset, binary, infer]
backend: pyg  # [nx, pyg]
max_nodes_display: 800000
figsize: [10, 10]



### baseline training dataset 

baselinedata_dir: 

# wsijson_to_trainset.py 
json_input_folder: 
output_baselineset:
tmp_dir: 
tile_size: 256
no_bbox: False 
generate_npz: True 
generate_png: True
png_level: 0 
png_overwrite: False
tilejson: True

# concat binaryformat 
concat:
  tiles_dir: 
  out_root: 
  folds: 1
  seed: 1337
  mask_key: type_map
  fold_index_starts_at_one: False
  num_classes: 6
  export_onehot_for_cellvit: True 
  # for binary format
  channel_map: {1: 4, 2: 5}
  ratio_threshold: 0
  stratify_by_major: True

# generate hovernet format 
hvn_format: 
  tiles_root: 
  hvn_format_output: 
  folds: 1
  seed: 1337
  packed_dtype: int32
  # for binary format
  ratio_threshold: 0 
  stratify_by_major: True








