defaults:
  - _self_

### all paths

json_folder: "/data/lsancere/Data_General/TrainingSets/GraphSet/TumSeg_OriginalRes/previous_steps/hvn_output_graphprocessing_1/"

pickle_output_folder: "/data/lsancere/Data_General/TrainingSets/GraphSet/TumSeg_OriginalRes/\
graphs/r50/"

conversion_output_folder: "/data/lsancere/Data_General/TrainingSets/GraphSet/TumSeg_OriginalRes/\
pyg_graphs/r50/"

simplifiedgraph_folder: "/data/lsancere/Data_General/TrainingSets/GraphSet/TumSeg_OriginalRes/\
simplified_pyg_graphs/r50/"

visualization_path: ""



### graphs

# generate graph (pickle format)
pickle_output_corename: "graph_r25_"
radius: 25
timing: True 

# graph simplification
max_hops: 3

# graph visualization
graphtype: dataset  #[dataset, binary, infer]
backend: pyg  # [nx, pyg]
max_nodes_display: 500000
figsize: [10, 10]





